title: 🌄 Journeys of Andrew Levin
description: 🌄 Journeys of Andrew Levin
url: "https://andrewalevin.github.io/journeys/"

# SEO image (optional)
logo: https://andrewalevin.github.io/journeys/preview.jpg

# SEO plugin
plugins:
  - jekyll-seo-tag